package com.Weather.WeatherAnalysis.Enums;

public enum Cities {
        AFGHANISTAN("Kabul"),
        ALBANIA("Tirana"),
        ALGERIA("Algiers"),
        ANDORRA("Andorra la Vella"),
        ANGOLA("Luanda"),
        ANTIGUA_AND_BARBUDA("Saint John’s"),
        ARGENTINA("Buenos Aires"),
        ARMENIA("Yerevan"),
        AUSTRALIA("Canberra"),
        AUSTRIA("Vienna"),
        AZERBAIJAN("Baku"),
        BAHAMAS("Nassau"),
        BAHRAIN("Manama"),
        BANGLADESH("Dhaka"),
        BARBADOS("Bridgetown"),
        BELARUS("Minsk"),
        BELGIUM("Brussels"),
        BELIZE("Belmopan"),
        BENIN("Porto-Novo"),
        BHUTAN("Thimphu"),
        BOLIVIA("Sucre"),
        BOSNIA_AND_HERZEGOVINA("Sarajevo"),
        BOTSWANA("Gaborone"),
        BRAZIL("Brasilia"),
        BRUNEI("Bandar Seri Begawan"),
        BULGARIA("Sofia"),
        BURKINA_FASO("Ouagadougou"),
        BURUNDI("Gitega"),
        CABO_VERDE("Praia"),
        CAMBODIA("Phnom Penh"),
        CAMEROON("Yaoundé"),
        CANADA("Ottawa"),
        CENTRAL_AFRICAN_REPUBLIC("Bangui"),
        CHAD("N’Djamena"),
        CHILE("Santiago"),
        CHINA("Beijing"),
        COLOMBIA("Bogotá"),
        COMOROS("Moroni"),
        COSTA_RICA("San José"),
        CROATIA("Zagreb"),
        CUBA("Havana"),
        CYPRUS("Nicosia"),
        CZECH_REPUBLIC("Prague"),
        DEMOCRATIC_REPUBLIC_OF_THE_CONGO("Kinshasa"),
        DENMARK("Copenhagen"),
        DJIBOUTI("Djibouti"),
        DOMINICA("Roseau"),
        DOMINICAN_REPUBLIC("Santo Domingo"),
        ECUADOR("Quito"),
        EGYPT("Cairo"),
        EL_SALVADOR("San Salvador"),
        EQUATORIAL_GUINEA("Malabo"),
        ERITREA("Asmara"),
        ESTONIA("Tallinn"),
        ESWATINI("Mbabane"),
        ETHIOPIA("Addis Ababa"),
        FIJI("Suva"),
        FINLAND("Helsinki"),
        FRANCE("Paris"),
        GABON("Libreville"),
        GAMBIA("Banjul"),
        GEORGIA("Tbilisi"),
        GERMANY("Berlin"),
        GHANA("Accra"),
        GREECE("Athens"),
        GRENADA("Saint George’s"),
        GUATEMALA("Guatemala City"),
        GUINEA("Conakry"),
        GUINEA_BISSAU("Bissau"),
        GUYANA("Georgetown"),
        HAITI("Port-au-Prince"),
        HONDURAS("Tegucigalpa"),
        HUNGARY("Budapest"),
        ICELAND("Reykjavik"),
        INDIA("New Delhi"),
        INDONESIA("Jakarta"),
        IRAN("Tehran"),
        IRAQ("Baghdad"),
        IRELAND("Dublin"),
        ISRAEL("Jerusalem"),
        ITALY("Rome"),
        IVORY_COAST("Yamoussoukro"),
        JAMAICA("Kingston"),
        JAPAN("Tokyo"),
        JORDAN("Amman"),
        KAZAKHSTAN("Astana"),
        KENYA("Nairobi"),
        KIRIBATI("Tarawa"),
        KOSOVO("Pristina"),
        KUWAIT("Kuwait City"),
        KYRGYZSTAN("Bishkek"),
        LAOS("Vientiane"),
        LATVIA("Riga"),
        LEBANON("Beirut"),
        LESOTHO("Maseru"),
        LIBERIA("Monrovia"),
        LIBYA("Tripoli"),
        LIECHTENSTEIN("Vaduz"),
        LITHUANIA("Vilnius"),
        LUXEMBOURG("Luxembourg"),
        MADAGASCAR("Antananarivo"),
        MALAWI("Lilongwe"),
        MALAYSIA("Kuala Lumpur"),
        MALDIVES("Malé"),
        MALI("Bamako"),
        MALTA("Valletta"),
        MARSHALL_ISLANDS("Majuro"),
        MAURITANIA("Nouakchott"),
        MAURITIUS("Port Louis"),
        MEXICO("Mexico City"),
        MICRONESIA("Palikir"),
        MOLDOVA("Chisinau"),
        MONACO("Monaco"),
        MONGOLIA("Ulaanbaatar"),
        MONTENEGRO("Podgorica"),
        MOROCCO("Rabat"),
        MOZAMBIQUE("Maputo"),
        MYANMAR("Naypyidaw"),
        NAMIBIA("Windhoek"),
        NAURU("Yaren District"),
        NEPAL("Kathmandu"),
        NETHERLANDS("Amsterdam"),
        NEW_ZEALAND("Wellington"),
        NICARAGUA("Managua"),
        NIGER("Niamey"),
        NIGERIA("Abuja"),
        NORTH_KOREA("Pyongyang"),
        NORTH_MACEDONIA("Skopje"),
        NORWAY("Oslo"),
        OMAN("Muscat"),
        PAKISTAN("Islamabad"),
        PALAU("Ngerulmud"),
        PANAMA("Panama City"),
        PAPUA_NEW_GUINEA("Port Moresby"),
        PARAGUAY("Asunción"),
        PERU("Lima"),
        PHILIPPINES("Manila"),
        POLAND("Warsaw"),
        PORTUGAL("Lisbon"),
        QATAR("Doha"),
        REPUBLIC_OF_THE_CONGO("Brazzaville"),
        ROMANIA("Bucharest"),
        RUSSIA("Moscow"),
        RWANDA("Kigali"),
        SAINT_KITTS_AND_NEVIS("Basseterre"),
        SAINT_LUCIA("Castries"),
        SAINT_VINCENT_AND_THE_GRENADINES("Kingstown"),
        SAMOA("Apia"),
        SAN_MARINO("San Marino"),
        SAO_TOME_AND_PRINCIPE("São Tomé"),
        SAUDI_ARABIA("Riyadh"),
        SENEGAL("Dakar"),
        SERBIA("Belgrade"),
        SEYCHELLES("Victoria"),
        SIERRA_LEONE("Freetown"),
        SINGAPORE("Singapore"),
        SLOVAKIA("Bratislava"),
        SLOVENIA("Ljubljana"),
        SOLOMON_ISLANDS("Honiara"),
        SOMALIA("Mogadishu"),
        SOUTH_AFRICA("Pretoria"),
        SOUTH_KOREA("Seoul"),
        SOUTH_SUDAN("Juba"),
        SPAIN("Madrid"),
        SRI_LANKA("Sri Jayawardenepura Kotte"),
        SUDAN("Khartoum"),
        SURINAME("Paramaribo"),
        SWEDEN("Stockholm"),
        SWITZERLAND("Bern"),
        SYRIA("Damascus"),
        TAIWAN("Taipei"),
        TAJIKISTAN("Dushanbe"),
        TANZANIA("Dodoma"),
        THAILAND("Bangkok"),
        TIMOR_LESTE("Dili"),
        TOGO("Lomé"),
        TONGA("Nukuʻalofa"),
        TRINIDAD_AND_TOBAGO("Port of Spain"),
        TUNISIA("Tunis"),
        TURKEY("Ankara"),
        TURKMENISTAN("Ashgabat"),
        TUVALU("Funafuti"),
        UGANDA("Kampala"),
        UKRAINE("Kyiv"),
        UNITED_ARAB_EMIRATES("Abu Dhabi"),
        UNITED_KINGDOM("London"),
        UNITED_STATES("Washington D.C."),
        URUGUAY("Montevideo"),
        UZBEKISTAN("Tashkent"),
        VANUATU("Port Vila"),
        VATICAN_CITY("Vatican City"),
        VENEZUELA("Caracas"),
        VIETNAM("Hanoi"),
        YEMEN("Sana’a"),
        ZAMBIA("Lusaka"),
        ZIMBABWE("Harare");

        private final String capital;

        Cities(String capital) {
            this.capital = capital;
        }

        @Override
        public String toString() {
            return capital;
        }




}
